### ISSUE TITLE
CI failing on macos due to nixpkgs issue with rustfmt

### ISSUE THREAD

**Issue by ModProg** [molybdenumsoftware/pr-tracker#3]
https://github.com/NixOS/nixpkgs/issues/273920

**Comment by jfly** [comment]
We attempted to bisect this here: https://gist.github.com/jfly/d64e46c0fe56b9daa60ac2751cc8b285

@Samyak2, can you continue the quest?

**Comment by Samyak2** [comment]
Will do!
